M_display: m_display__util Module Reference
m_display__util Module Reference
Data Types
type boxlist
type boxnode
type disp_settings
type settings
type tostring_settings
Functions/Subroutines
subroutine, public check_settings ()
logical function number_rows (SE)
logical function number_cols (SE)
subroutine, public preparebox (title, SE, m, n, wid, widp, lin1, wleft, boxp)
subroutine, public copytobox (s, lin1, widj, widpj, nblj, boxp, wleft)
subroutine, public copyseptobox (sep, m, lin1, boxp, wleft)
subroutine copycolumnnumberstobox (s, wleft, wid, widp, lsep, boxp, lin1)
subroutine, public finishbox (title, SE, boxp)
subroutine, public find_editdesc_real (exp, expm, dmx, edesc, flen, ndec, posit)
pure subroutine, public readfmt (fmt, fmt1, w, d, gedit)
pure subroutine, public replace_w (fmt, wnew)
subroutine, public get_se (SE, title, shapex, fmt, advance, lbound, separator, style, trim, unit, orient, zeroas, digmax)
subroutine getstyles (style, tsty, tch, number, ok)
subroutine, public replace_zeronaninf (s, zas, maskz, masknan, maskminf, maskinf)
pure character(len(s)) function, public upper (s)
pure subroutine sszipfmt (fmt, fmt1)
pure integer function, public nnblk (s)
subroutine, public disp_errmsg (s)
subroutine, public tostring_check_settings
pure subroutine, public trim_s_real (sa, gedit, w)
pure subroutine, public trim_real (sa, gedit, w)
pure subroutine, public tostring_get (sa, st)
pure subroutine, public tostring_get_complex (sar, sgn, sai, st)
type(boxlist) function, pointer getboxlist (unit)
subroutine clearboxlist (unit)
subroutine newbox (unit, m, n, boxp)
character(size(a)) function tostr (a)
subroutine dispboxlist (unit, sep)
subroutine dispnewline (unit)
Variables
type(disp_settings), save, public defset
type(disp_settings), save, public factory_settings
type(tostring_settings), save, public tosset
type(tostring_settings), save, public tosfac
character(*), parameter, public errormsg = 'Illegal format'
type(boxlist), pointer firstboxlist => null()
Detailed Description
NAME
M_display(3f) - [M_display::INTRO] module for pretty-printing matrices
INTRODUCTION
M_display is a standard Fortran 95 module for quick and easy displaying of numbers, vectors or matrices using default or specified format. It can be useful for debugging purposes, for preliminary display of numerical results, and even for final display of such results in cases when carefully formatted tables are not needed. It is comparable to the automatic matrix printing of Matlab, S and R, but offers substantially more control over the format used.
The module can handle the standard Fortran data types integer, single precision, double precision, complex, logical and character. Integer, real, complex and logical data of other than default kind are supported with add-on modules. The module contains the following public procedures:
Subroutine DISP                  The main procedure used for displaying items
Subroutine DISP_SET              Used to change default settings for DISP
Subroutine DISP_SET_FACTORY      Restores DISP-settings to original (factory) default
Function DISP_GET                Returns a structure with current DISP-settings
Function TOSTRING                Returns a string representation of a scalar or vector
Subroutine TOSTRING_SET          Used to change default settings for TOSTRING
Subroutine TOSTRING_SET_FACTORY  Restores TOSTRING-settings to original default
In addition the module defines a public derived type, DISP_SETTINGS, used for saving and restoring settings for DISP. The procedures DISP and TOSTRING have a generic interface and optional arguments, so the same subroutine / function name, is used to display items of different data types and ranks, with or without labels, and using default or specified format. Similarly DISP_SET is generic and can be used both to change individual settings and to restore previously saved settings.
The most basic calling syntax for displaying is CALL DISP(expression) which will display the expression with default format. The format may be specified with CALL DISP(expression, edit- descriptor), and CALL DISP(title, expression) will label the displayed item with a title. Examples are CALL DISP(A), CALL DISP(A,'F9.3'), CALL DISP('A=',A) and CALL DISP('A=',A,'F9.3'), the last one specifying both title and format. If aij = exp(i + j - 1), i, j = 1,...,4, then CALL DISP('A = ', A) writes out:
 > A =  2.72    7.39   20.09    54.60
 >      7.39   20.09   54.60   148.41
 >     20.09   54.60  148.41   403.43
 >     54.60  148.41  403.43  1096.63
and if bij = exp(i*j) the result of CALL DISP(B) is:
 > 2.71828E+0  7.38906E+0  2.00855E+1  5.45981E+1
 > 7.38906E+0  5.45981E+1  4.03429E+2  2.98096E+3
 > 2.00855E+1  4.03429E+2  8.10308E+3  1.62755E+5
 > 5.45981E+1  2.98096E+3  1.62755E+5  8.88611E+6.
It is also possible to number the rows and columns: CALL DISP(A, STYLE='NUMBER') will give:
 >      1       2       3        4
 > 1   2.72    7.39   20.09    54.60
 > 2   7.39   20.09   54.60   148.41
 > 3  20.09   54.60  148.41   403.43
 > 4  54.60  148.41  403.43  1096.63.
The selection between F and E editing depends on the size of the largest displayed element as discussed in section 3.2 below. Among the settings that may be controlled is the spacing between columns, the number of significant digits, the placement of the label, and the file unit where the output goes. Items can in addition be displayed side by side, for example:
 > CALL DISP('X = ', X, ADVANCE='NO')
 > CALL DISP('Y = ', Y)
which might output:
 > X = 7  8  3   Y = 11
 >     4  0  2        2
 >     1  3  6        7
Complex numbers are formatted as illustrated by:
 > COMPLEX C(3,3)
 > FORALL(I=1:3, K=1:3) C(I,K)=LOG(CMPLX(-I*K))**K
 > CALL DISP('C = ', C, 'F0.3')
which will display
 > C = 0.000 + 3.142i   -9.389 +  4.355i   -31.203 - 19.631i
 >     0.693 + 3.142i   -7.948 +  8.710i   -47.300 -  0.749i
 >     1.099 + 3.142i   -6.659 + 11.258i   -54.449 + 14.495i
infinite and not-a-number real values are supported and displayed as nan, +inf or -inf.
the remaining sections in this user manual contain detailed information on using the module. section 2 discusses the basics of using the module, including use statements, compiling and linking, and add-on modules supporting non-default kinds of data. section 3 gives a detailed description of the generic subroutine disp. all the possible arguments are listed and the purpose of each one described. section 4 describes how to change various settings that control how items are displayed with disp. section 5 describes the function tostring which may be used to change numbers to strings. finally testing of the module is discussed in section 6.
OVERVIEW OF MODULES
The file M_display.f90 actually begins with two auxiliary modules, M_display__PUTSTRMODULE and M_display__UTIL. The first one contains two dummy subroutines, PUTSTR and PUTNL, which do nothing, but must be incorporated to avoid an "undefined symbol" link error. In addition it defines the named constant (parameter) DEFAULT_UNIT = -3, which makes the asterisk unit (usually the screen) the default to display on.
Alternatively the user can write his own M_display__PUTSTRMODULE as described below. An example is near the beginning of M_display.f90 (commented out) and also in the file putstrmodule_mex.f90, enclosed with the package. It may be used (commented in instead of the default one) to allow Matlab mex files to display in the Matlab command window.
AN EXAMPLE PROGRAM
Following is a short example program that uses the package:
  program example
    use M_display
    real :: a(3) = [ 1.2345, 2.3456, 3.4567 ]
    call disp('A = ', A, SEP=', ', ORIENT = 'ROW')
  end program example
The program should write out "A = 1.23450, 2.34560, 3.45670".
A longer example program:
program demo_M_display use M_display implicit none integer, parameter :: rk = selected_real_kind(6), n = 3 real(rk) :: a(n,n), b(n,n), x integer i, j, k(5) call disp_set(advance = 'double') forall(i=1:n, j=1:n) a(i,j) = exp(real(i+j-1, rk)) b(i,j) = exp(real(i**j, rk)) end forall call disp('A = ', a) call disp(b) call disp(a(1:2,:),'f0.5') call disp('MATRIX', a, style='UNDERLINE & NUMBER', unit=-3, digmax=4) k = [-3,0,12,14,0] call disp('K', k, style='pad', orient='row', sep=' ', zeroas='.') x = 1.5 call disp('The square of '//tostring(x)//' is '//tostring(x*x)) call disp_set(matsep = ' | ') call disp([11,12,13], advance='no') call disp([.true., .false., .true.], advance='no') call disp(['A','B','C']) end program demo_M_display
Expected results:
> A =  2.718   7.389   20.086
>      7.389  20.086   54.598
>     20.086  54.598  148.413
>
> 2.71828E+00  2.71828E+00  2.71828E+00
> 7.38906E+00  5.45982E+01  2.98096E+03
> 2.00855E+01  8.10308E+03  5.32048E+11
>
> 2.71828   7.38906  20.08554
> 7.38906  20.08554  54.59815
>
>        MATRIX
> --------------------
>      1     2      3
> 1   2.7   7.4   20.1
> 2   7.4  20.1   54.6
> 3  20.1  54.6  148.4
>
> ------K-----
> -3 . 12 14 .
>
> The square of 1.5 is 2.25
>
> 11 | T | A
> 12 | F | B
> 13 | T | C
AUTHOR
Based on dispmodule(3f), "A Fortran 95 module for pretty-printing matrices". Version number 1.02 6-Sept-2008, Kristjan Jonasson, Dept. of Computer Science, University of Iceland (jonas.nosp@m.son@.nosp@m.hi.is).
Function/Subroutine Documentation
check_settings()
subroutine, public m_display__util::check_settings
References defset, disp_errmsg(), and getstyles().
clearboxlist()
subroutine m_display__util::clearboxlist (integer, intent(in) unit) private
References firstboxlist.
copycolumnnumberstobox()
subroutine m_display__util::copycolumnnumberstobox (character(*), dimension(:), intent(in) s, integer, intent(in) wleft, integer, dimension(:), intent(in) wid, integer, dimension(:), intent(in) widp, integer, intent(in) lsep, character, dimension(:,:), intent(inout) boxp, integer, intent(inout) lin1) private
copyseptobox()
subroutine, public m_display__util::copyseptobox (character(*), intent(in) sep, integer, intent(in) m, integer, intent(in) lin1, character, dimension(:,:), intent(inout) boxp, integer, intent(inout) wleft)
copytobox()
subroutine, public m_display__util::copytobox (character(*), dimension(:), intent(in) s, integer, intent(in) lin1, integer, intent(in) widj, integer, intent(in) widpj, integer, intent(in) nblj, character, dimension(:,:), intent(inout) boxp, integer, intent(inout) wleft)
disp_errmsg()
subroutine, public m_display__util::disp_errmsg (character(*), intent(in) s)
References copytobox(), m_display__putstrmodule::default_unit, dispboxlist(), and newbox().
dispboxlist()
subroutine m_display__util::dispboxlist (integer, intent(in) unit, character(*), intent(in) sep) private
References clearboxlist(), dispnewline(), getboxlist(), m_display__putstrmodule::putstr(), and tostr().
dispnewline()
subroutine m_display__util::dispnewline (integer, intent(in) unit) private
References m_display__putstrmodule::putnl().
find_editdesc_real()
subroutine, public m_display__util::find_editdesc_real (integer, intent(inout) exp, integer, intent(in) expm, integer, intent(in) dmx, character(14), intent(out) edesc, integer, intent(out) flen, integer, intent(out) ndec, logical, intent(in) posit)
finishbox()
subroutine, public m_display__util::finishbox (character(*), intent(in) title, type(settings), intent(in) SE, character, dimension(:,:), intent(inout) boxp)
References defset, dispboxlist(), dispnewline(), number_cols(), and upper().
get_se()
subroutine, public m_display__util::get_se (type(settings), intent(out) SE, character(*), intent(in) title, integer, dimension(:), intent(in) shapex, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional separator, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient, character(*), intent(in), optional zeroas, integer, intent(in), optional digmax)
References defset, disp_errmsg(), getstyles(), readfmt(), trims(), and upper().
getboxlist()
type(boxlist) function, pointer m_display__util::getboxlist (integer, intent(in) unit) private
References firstboxlist.
getstyles()
subroutine m_display__util::getstyles (character(*), intent(in) style, character(9), intent(out) tsty, character(1), intent(out) tch, logical, intent(out) number, logical, intent(out) ok) private
References upper().
newbox()
subroutine m_display__util::newbox (integer, intent(in) unit, integer, intent(in) m, integer, intent(in) n, character, dimension(:,:), pointer boxp) private
References getboxlist().
nnblk()
pure integer function, public m_display__util::nnblk (character(*), intent(in) s)
number_cols()
logical function m_display__util::number_cols (type(settings), intent(in) SE) private
number_rows()
logical function m_display__util::number_rows (type(settings), intent(in) SE) private
preparebox()
subroutine, public m_display__util::preparebox (character(*), intent(in) title, type(settings), intent(in) SE, integer, intent(in) m, integer, intent(in) n, integer, dimension(:), intent(inout) wid, integer, dimension(:), intent(out) widp, integer, intent(out) lin1, integer, intent(out) wleft, character, dimension(:,:), pointer boxp)
References copycolumnnumberstobox(), copyseptobox(), copytobox(), newbox(), number_cols(), number_rows(), replace_w(), and upper().
readfmt()
pure subroutine, public m_display__util::readfmt (character(*), intent(in) fmt, character(*), intent(out) fmt1, integer, intent(out) w, integer, intent(out) d, logical, intent(out) gedit)
References sszipfmt(), and upper().
replace_w()
pure subroutine, public m_display__util::replace_w (character(*), intent(inout) fmt, integer, intent(in) wnew)
replace_zeronaninf()
subroutine, public m_display__util::replace_zeronaninf (character(*), dimension(:), intent(inout) s, character(*), intent(in) zas, logical, dimension(:), intent(in) maskz, logical, dimension(:), intent(in), optional masknan, logical, dimension(:), intent(in), optional maskminf, logical, dimension(:), intent(in), optional maskinf)
sszipfmt()
pure subroutine m_display__util::sszipfmt (character(*), intent(in) fmt, character(*), intent(out) fmt1) private
tostr()
character(size(a)) function m_display__util::tostr (character, dimension(:), intent(in) a) private
tostring_check_settings()
subroutine, public m_display__util::tostring_check_settings
References disp_errmsg(), readfmt(), tosfac, and tosset.
tostring_get()
pure subroutine, public m_display__util::tostring_get (character(*), dimension(:), intent(in) sa, character(*), intent(out) st)
References tosset.
tostring_get_complex()
pure subroutine, public m_display__util::tostring_get_complex (character(*), dimension(:), intent(in) sar, character(*), dimension(*), intent(in) sgn, character(*), dimension(:), intent(in) sai, character(*), intent(out) st)
References tosset.
trim_real()
pure subroutine, public m_display__util::trim_real (character(*), dimension(:), intent(inout) sa, logical, intent(in) gedit, integer, intent(in) w)
References tosset, and trim_s_real().
trim_s_real()
pure subroutine, public m_display__util::trim_s_real (character(*), intent(inout) sa, logical, intent(in) gedit, integer, intent(in) w)
References tosset.
upper()
pure character(len(s)) function, public m_display__util::upper (character(*), intent(in) s)
Variable Documentation
defset
type(disp_settings), save, public m_display__util::defset
errormsg
character(*), parameter, public m_display__util::errormsg = 'Illegal format'
factory_settings
type(disp_settings), save, public m_display__util::factory_settings
firstboxlist
type(boxlist), pointer m_display__util::firstboxlist => null() private
tosfac
type(tostring_settings), save, public m_display__util::tosfac
tosset
type(tostring_settings), save, public m_display__util::tosset