M_uuid: m_uuid Module Reference
m_uuid Module Reference
generate_uuid(3f) was originally derived from the xmlf90 codebase, (c) Alberto Garcia & Jon Wakelin, 2003-2004. It also calls RNG routines from Scott Ladd scott.nosp@m..lad.nosp@m.d@coy.nosp@m.oteg.nosp@m.ulch..nosp@m.com, and the libFoX modules. Although some sections have been replaced, generate_uuid(3f) was originally based on the libFoX version, with licensing as follows:
Data Types
type mtprng_state
Functions/Subroutines
character(len=36) function, public generate_uuid (version)
integer(kind=i8b) function get_utc_since_1582 (values)
subroutine date_to_julian (dat, julian, ierr)
subroutine date_to_unix (dat, unixtime, ierr)
subroutine mtprng_init (seed, state)
integer(int64) function mtprng_rand64 (state)
Variables
integer, parameter realtime =kind(0.0d0)
integer, parameter ieee32 = selected_real_kind(6, 37)
integer, parameter ieee64 = selected_real_kind(15, 307)
integer(int32), parameter n = 624_INT32
integer(int32), parameter m = 397_INT32
real(kind=realtime), parameter, private secday =86400.0d0
integer, parameter i4b = selected_int_kind(9)
integer, parameter i8b = selected_int_kind(18)
type(mtprng_state), save rng_state
logical, save initialized = .false.
integer, save values_save
integer(kind=i4b), save hires_count = 0
integer, save clock_seq = 0
Detailed Description
generate_uuid(3f) was originally derived from the xmlf90 codebase, (c) Alberto Garcia & Jon Wakelin, 2003-2004. It also calls RNG routines from Scott Ladd scott.nosp@m..lad.nosp@m.d@coy.nosp@m.oteg.nosp@m.ulch..nosp@m.com, and the libFoX modules. Although some sections have been replaced, generate_uuid(3f) was originally based on the libFoX version, with licensing as follows:
(c) 2005-2009 Toby White <tow@uszla.me.uk>
(c) 2007-2009 Gen-Tao Chiang <gtc25@cam.ac.uk>
(c) 2008-2012 Andrew Walker <a.walker@ucl.ac.uk>
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
This software is provided by the copyright holders and contributors "AS IS" and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose are disclaimed. in no event shall the copyright owner or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage.
Function/Subroutine Documentation
date_to_julian()
subroutine m_uuid::date_to_julian (integer, dimension(8), intent(in) dat, real(kind=realtime), intent(out) julian, integer, intent(out) ierr) private
NAME
date_to_julian(3f) - [M_time:JULIAN] converts DAT date-time array to Julian Date (LICENSE:PD)
SYNOPSIS
subroutine date_to_julian(dat,juliandate,ierr)
 integer,intent(in)               :: dat(8)
 real(kind=realtime),intent(out)  :: juliandate
 integer,intent(out)              :: ierr
DESCRIPTION
Converts a DAT date-time array to a Unix Epoch Time (UET) value. UET is the number of seconds since 00:00 on January 1st, 1970, UTC.
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f):
dat=[ year,month,day,timezone,hour,& & minutes,seconds,milliseconds]
RETURNS
juliandate A Julian Ephemeris Date (JED) is the number of days since noon (not midnight) on January 1st, 4713 BC. ierr Error code. If 0 no error occurred.
EXAMPLE
Sample Program:
 program demo_date_to_julian
 use M_time, only : date_to_julian,realtime
 implicit none
 integer             :: dat(8)
 real(kind=realtime) :: juliandate
 integer             :: ierr
    ! generate DAT array
    call date_and_time(values=dat)
    ! show DAT array
    write(*,'(" Today is:",*(i0:,":"))')dat
    ! convert DAT to Julian Date
    call date_to_julian(dat,juliandate,ierr)
    write(*,*)'Julian Date is ',juliandate
    write(*,*)'ierr is ',ierr
 end program demo_date_to_julian
results:
 Today is:2016:7:19:-240:11:3:13:821
 Julian Date is    2457589.1272432986
 ierr is            0
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
Parameters
[in] dat AUTHOR: John S. Urban
VERSION: 1.0 2015-12-21
REFERENCE: From Wikipedia, the free encyclopedia 2015-12-19
date_to_unix()
subroutine m_uuid::date_to_unix (integer, dimension(8), intent(in) dat, real(kind=realtime), intent(out) unixtime, integer, intent(out) ierr) private
NAME
date_to_unix(3f) - [M_time:UNIX_EPOCH] converts DAT date-time array to Unix Epoch Time (LICENSE:PD)
SYNOPSIS
subroutine date_to_unix(dat,unixtime,ierr)
 integer,intent(in)               :: dat(8)
 real(kind=realtime),intent(out)  :: unixtime
 integer,intent(out)              :: ierr
DESCRIPTION
Converts a DAT date-time array to a UET (Unix Epoch Time).
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f):
dat=[ year,month,day,timezone,hour,&
 & minutes,seconds,milliseconds]
RETURNS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC. ierr Error code. If 0 no error occurred.
EXAMPLE
 Sample program:
  program demo_date_to_unix
  use M_time, only : date_to_unix, realtime
  implicit none
  integer             :: dat(8)
  real(kind=realtime) :: unixtime
  integer             :: ierr
     call date_and_time(values=dat)
     write(*,'(" Today is:",*(i0:,":"))')dat
     call date_to_unix(dat,unixtime,ierr)
     write(*,*)'Unix Epoch time is ',unixtime
     write(*,*)'ierr is ',ierr
  end program demo_date_to_unix
 results:
  Today is:2016:7:18:-240:23:44:20:434
  Unix Epoch time is    1468899860.4340105
  ierr is            0
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References date_to_julian(), and secday.
generate_uuid()
character(len=36) function, public m_uuid::generate_uuid (integer, intent(in), optional version)
NAME
generate_uuid(3f) - [M_uuid] generate a UUID (Universally Unique IDentifier) string per RFC 4122 (LICENSE:BSD-4-Clause)
SYNOPSIS
function generate_uuid(version) result(uuid)
 integer, intent(in), optional :: version
 character(len=36) :: uuid
DESCRIPTION
A universally unique identifier (UUID) is a 128-bit number used to identify information in computer systems. When generated according to standard methods UUIDs are for practical purposes unique. generate_uuid(3f) converts the UUID to a standard string format per RFC 4122.
AUTHORS
based on previous work from Alberto Garcia & Jon Wakelin, 2003-2004. RNG routines from Scott Ladd scott.nosp@m..lad.nosp@m.d@coy.nosp@m.oteg.nosp@m.ulch..nosp@m.com, and the libFoX library(Toby White tow@u.nosp@m.szla.nosp@m..me.u.nosp@m.k, Gen-Tao Chiang gtc25.nosp@m.@cam.nosp@m..ac.u.nosp@m.k, Andrew Walker a.wal.nosp@m.ker@.nosp@m.ucl.a.nosp@m.c.uk).
OPTIONS
version Indicates which standard method as described in RFC 4122 is used to generate the string. Versions 0,1, and 4 are supported.
0. Nil UUID (ie. '00000000-0000-0000-0000-000000000000')
time-based UUID
Not implemented
Not implemented
pseudo-RNG(Random Number Generator) based
Not implemented
EXAMPLE
Sample usage:
program demo_generate_uuid use M_uuid, only : generate_uuid implicit none character(len=36) :: uuid ! uuid=generate_uuid(1) ! version 1 (time-based UUID) write(*,'(a36)')uuid ! uuid=generate_uuid(4) ! version 4 (pseudo-RNG-based), default ! ! RFC 4122 defines a Uniform Resource Name (URN) namespace for UUIDs. write(*,'("urn:uuid:",a36)')uuid ! ! a good scratch file name open(file='/tmp/scratch_'//uuid,unit=10) ! end program demo_generate_uuid
Typical output:
e769adf4-4af7-11e8-7421-3c9dfbfe9aab urn:uuid:5b0946b8-0eb4-4966-619d-047b7f7e2056
References clock_seq, get_utc_since_1582(), hires_count, i4b, initialized, int32tohexoctets(), int64tohexoctets(), mtprng_init(), mtprng_rand64(), rng_state, and values_save.
get_utc_since_1582()
integer(kind=i8b) function m_uuid::get_utc_since_1582 (integer, dimension(8), intent(in) values) private
References date_to_unix(), and i8b.
mtprng_init()
subroutine m_uuid::mtprng_init (integer(int32), intent(in) seed, type(mtprng_state), intent(out) state) private
NAME
mtprng_init(3f) - [M_random:MERSENNE TWISTER] Initialize the Mersenne Twister random number generator with "seed" (LICENSE:BSD-4-Clause)
SYNOPSIS
subroutine mtprng_init(seed, state)
integer(INT32),     intent(in)  :: seed
type(mtprng_state), intent(out) :: state
DESCRIPTION
Initializes the Mersenne Twister random number generator with "seed"
OPTIONS
seed A seed value is used to start a specific sequence of pseudo-random numbers state generator state initialized by mtprng_init(3f) or mtprng_init_array(3f)
EXAMPLE
Sample program:
program demo_mtprng_init use M_random, only : mtprng_state, mtprng_init, mtprng_rand64 use, intrinsic :: iso_fortran_env, only : int32, int64 implicit none integer(INT32) :: seed type(mtprng_state) :: state GET_SEED: block integer :: count integer :: count_rate call system_clock(count, count_rate) seed=count endblock GET_SEED call mtprng_init(seed, state) ! returns a INT64 integer with a range in 0 .. 2^32-1 write(*,*) mtprng_rand64(state) end program demo_mtprng_init
Sample Results:
867010878
References n.
mtprng_rand64()
integer(int64) function m_uuid::mtprng_rand64 (type(mtprng_state), intent(inout) state) private
NAME
mtprng_rand64(3f) - [M_random:MERSENNE TWISTER] Obtain the next 64-bit integer in the pseudo-random sequence (LICENSE:BSD-4-Clause)
SYNOPSIS
function mtprng_rand64(state) result(r)
type(mtprng_state), intent(inout) :: state
integer(INT64) :: r
DESCRIPTION
Obtain the next 64-bit integer in the pseudo-random sequence in the range 0 to 2^32-1. Note that the range is considerably below the value of HUGE(0_int64).
OPTIONS
state generator state initialized by mtprng_init(3f) or mtprng_init_array(3f)
RETURNS
r next pseudo-random value in the range 0 to 2^32-1
EXAMPLE
Sample program:
program demo_mtprng_rand64 use M_random, only : mtprng_state, mtprng_init, mtprng_rand64 use, intrinsic :: iso_fortran_env, only : int32, int64 implicit none integer(INT32) :: seed type(mtprng_state) :: state GET_SEED: block integer :: count integer :: count_rate call system_clock(count, count_rate) seed = count endblock GET_SEED call mtprng_init(seed, state) write(*,*) mtprng_rand64(state) end program demo_mtprng_rand64
References m, mtprng_init(), and n.
Variable Documentation
clock_seq
integer, save m_uuid::clock_seq = 0 private
hires_count
integer(kind=i4b), save m_uuid::hires_count = 0 private
i4b
integer, parameter m_uuid::i4b = selected_int_kind(9) private
i8b
integer, parameter m_uuid::i8b = selected_int_kind(18) private
ieee32
integer, parameter m_uuid::ieee32 = selected_real_kind(6, 37)
ieee64
integer, parameter m_uuid::ieee64 = selected_real_kind(15, 307)
initialized
logical, save m_uuid::initialized = .false. private
m
integer(int32), parameter m_uuid::m = 397_INT32
n
integer(int32), parameter m_uuid::n = 624_INT32
realtime
integer, parameter m_uuid::realtime =kind(0.0d0)
NAME
M_uuid(3f) - [M_uuid] a module of UUID (Universally Unique IDentifier) procedures (LICENSE:BSD-4-Clause)
SYNOPSIS
use m_uuid, only : generate_uuid
QUOTE
Remember you are unique, just like everyone else.
DESCRIPTION
A universally unique identifier (UUID) is a 128-bit number used to
identify information in computer systems.
When generated according to the standard methods, UUIDs are for
practical purposes unique, without depending for their uniqueness
on a central registration authority or coordination between the
parties generating them, unlike most other numbering schemes. While
the probability that a UUID will be duplicated is not zero, it is
close enough to zero to be negligible.
Thus, anyone can create a UUID and use it to identify something with
near certainty that the identifier does not duplicate one that has
already been or will be created to identify something else. Information
labeled with UUIDs by independent parties can therefore be later
combined into a single database, or transmitted on the same channel,
without needing to resolve conflicts between identifiers.
Adoption of UUIDs and GUIDs is widespread. Many computing platforms
provide support for generating them, and for parsing their textual
representation.
RFC 4122 defines a Uniform Resource Name (URN) namespace for UUIDs.
A UUID presented as a URN appears as follows:
   urn:uuid:123e4567-e89b-12d3-a456-426655440000
– Wikipedia
PROCEDURES
generate_uuid(version)   generate 36-character UUID string
rng_state
type(mtprng_state), save m_uuid::rng_state private
secday
real(kind=realtime), parameter, private m_uuid::secday =86400.0d0 private
values_save
integer, save m_uuid::values_save private